ap.apmanager.item_sent=you sent %s to %s.
ap.apmamnger.item_received=you receive %s from %s.
ap.apmanager.search_disabled=you haven't unlocked search yet!

scenes.heroselectscene.hero_locked=you haven't unlocked %s yet!